name: PumpkinRitualDupe
version: '4.0'
main: org.First.pumpkinRitualDupe.PumpkinRitualDupe
api-version: '1.18'
authors: [_MasterZero]
description: A spooky Halloween pumpkin ritual dupe with random chance and configurable settings.

commands:
  pumpkindupe:
    description: Manage PumpkinRitualDupe (reload config)
    usage: /pumpkindupe reload

permissions:
  pumpkindupe.reload:
    description: Reload PumpkinRitualDupe configuration
    default: op
